<?php

/**
 * PluginsfTrafficCMSI18nSubPageTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginsfTrafficCMSI18nSubPageTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginsfTrafficCMSI18nSubPageTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginsfTrafficCMSI18nSubPage');
    }
}