<?php

/**
 * PluginsfTrafficCMSImageTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginsfTrafficCMSImageTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginsfTrafficCMSImageTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginsfTrafficCMSImage');
    }
}