<?php

/**
 * PluginsfTrafficCMSSubPageTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginsfTrafficCMSSubPageTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginsfTrafficCMSSubPageTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginsfTrafficCMSSubPage');
    }
}