<?php

/**
 * PluginsfTrafficCMSSeoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginsfTrafficCMSSeoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginsfTrafficCMSSeoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginsfTrafficCMSSeo');
    }
}