<?php

/**
 * PluginsfTrafficCMSI18nSeoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginsfTrafficCMSI18nSeoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginsfTrafficCMSI18nSeoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginsfTrafficCMSI18nSeo');
    }
}