<?php

/**
 * PluginsfTrafficCMSContent
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PluginsfTrafficCMSContent extends BasesfTrafficCMSContent
{
  
  public function getValueSnippet($length = 500)
  {
    $str = $this->value;
    
    if (strlen($str) > $length)
    {
      $str = substr($str, 0, $length) . '...';
    }
    
    return $str;
  }
  
  public function getValue()
  {
    $value = $this->_get('value');
    
    if ($this->type == 'float')
    {
      $value = sprintf("%.2f", $value);
    }
    
    return $value;
  }
}