generator:
  class: sfDoctrineGenerator
  param:
    model_class:           sfTrafficCMSPage
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          sf_traffic_cms_page
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        title:      Static Pages
        display:    [ =title, created_at, updated_at ]
        actions:    {}
        batch_actions:    {}
        object_actions:   { _edit: ~ }
      filter:
        display:    [ =title, body_copy, created_at, updated_at ]
      form:    ~
      edit:
        title: Editing %%title%%
        actions:
          _list: ~
          _save: ~
      new:     ~
