sfTrafficCMSPluginDeleteChildren:
  url:   /sf_traffic_cms_plugin/delete_children/:model/:id/:parent_model/:parent_model_id
  param: { module: sfTrafficCMSPlugin, action: deleteChildren }

simple_sub_page:
  url:  /:parentslug/:slug
  params: { module: sfTrafficCMSPlugin, action: showSubPage }