sfTrafficCMSPage:
  actAs:
    Sluggable:
      fields: [ title ]
    TrafficCMS: ~
    Timestampable: ~
  columns:
    title:            { type: string(250), notnull: true }
    route:            { type: string(250) }
    meta_keywords:    { type: string(250) }
    meta_description: { type: string(250) }
    body_copy:        { type: string(10000) }
    has_sub_pages:    { type: boolean, notnull: true, default: false }

sfTrafficCMSSubPage:
  actAs:
    Sluggable:
      fields: [ title ]
    TrafficCMS: ~
    Timestampable: ~
  columns:
    title:            { type: string(250), notnull: true }
    parent_id:        { type: integer, notnull: false }
    route:            { type: string(250) }
    meta_keywords:    { type: string(250) }
    meta_description: { type: string(250) }
    body_copy:        { type: string(10000) }
  relations:
    Parent:
      class: sfTrafficCMSPage
      local: parent_id
      foreignAlias: SubPages


sfTrafficCMSSeo:
  actAs:
    Timestampable: ~
    TrafficCMS: ~
  columns:
    page_name:        { type: string(250) }
    title:            { type: string(250) }
    url:              { type: string(100) }
    route:            { type: string(250) }
    meta_keywords:    { type: string(250) }
    meta_description: { type: string(250) }
